name: push-actions
on:
  push:
    branches: ["main", "release-*"]

jobs:
  gh-actions-integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/create-sap-btp-kyma
        id: create-btp-resources
        with:
          btp_subaccount_name: tf-actions-${{ github.sha }}-${{ github.run_attempt }}
          btp_backend_url: '${{ secrets.btp_api_url }}'
          btp_user: '${{ secrets.username }}'
          btp_password: '${{ secrets.password }}'
          btp_global_account: '${{ secrets.global_account }}'
          btp_idp_tenant: '${{ secrets.ias_tenant }}'
          btp_subaccount_region: '${{ secrets.sa_region }}'
          btp_kyma_region: '${{ secrets.kyma_region }}'
          btp_kyma_plan: '${{ secrets.kyma_plan }}'
          btp_kyma_modules: "[]"
          btp_kyma_autoscaler_min: 3
      - name: kyma environment sanity check
        run: |
          kubectl get nodes
      - uses: ./.github/actions/force-delete-sap-btp-subaccount
        if: always()
        with:
          btp_subaccount_id: ${{ steps.create-btp-resources.outputs.subaccount_id }}
          btp_backend_url: ${{ secrets.btp_api_url}}
          btp_user: ${{ secrets.username}}
          btp_password: ${{ secrets.password}}
          btp_global_account: ${{ secrets.global_account }}
          btp_idp_tenant: ${{ secrets.ias_tenant }}
